# This will keep the tag:latest up-to-date with all commits and pull requests

name: Test PR for Docker build and run

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]
jobs:
  test_docker_build:
    name: Test docker-compose up with build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose up
        run: docker-compose -f docker-compose_build.yml up -d
      - name: Wait and check log
        run: |
          test_case=" INFO at api.py:65: Local API listening for requests at 4cat_backend:4444"
          sleep 30 && var=$(docker exec 4cat_backend tail -n 1 logs/backend_4cat.log)
          if [ "$(echo "$var" | tr "|" "\n" | sed -n '2p')" = "$test_case" ]; then echo "::debug::Backend running as expected"; else echo "::error::Backend failed to start"; fi
